
def sum_even_fibs( ceiling )
  sum = 0
  current = last = 1
  current, last, sum = current+last, current, (current.even? ? sum+current : sum) until current > ceiling 
  return sum
end
  
=begin
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
=end